name: distance_route
description: A Flutter package for calculating and displaying routes with Google Maps.
version: 0.0.4
homepage: https://amarj234.github.io/
repository: https://github.com/Amarj234/map_route_package.git

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.4.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
